In [1]:
import pandas as pd

# Criando a base de dados de funcionários, departamentos e salários
dados_rh = {
    'Funcionario': [
        'Ana Silva', 'Bruno Souza', 'Carlos Lima', 'Daniela Costa', 'Eduardo Santos',
        'Fernanda Oliveira', 'Gabriel Pereira', 'Helena Rocha', 'Igor Martins', 'Juliana Alves',
        'Lucas Carvalho', 'Mariana Ribeiro', 'Nicolas Cardoso', 'Patrícia Mendes', 'Rafael Barbosa',
        'Sofia Freitas', 'Thiago Araujo', 'Vanessa Ramos', 'Wagner Castro', 'Larissa Correia'
    ] * 5, # Repetindo para gerar 100 registros
    
    'Departamento': [
        'Tecnologia', 'Recursos Humanos', 'Financeiro', 'Marketing', 'Operações',
        'Tecnologia', 'Financeiro', 'Marketing', 'Recursos Humanos', 'Operações',
        'Tecnologia', 'Financeiro', 'Recursos Humanos', 'Marketing', 'Operações',
        'Tecnologia', 'Financeiro', 'Marketing', 'Recursos Humanos', 'Operações'
    ] * 5,
    
    'Salario': [
        8500.00, 4200.00, 6100.00, 4800.00, 3500.00,
        12500.00, 7200.00, 5100.00, 4300.00, 3200.00,
        9100.00, 6800.00, 4600.00, 4900.00, 3800.00,
        11000.00, 5900.00, 5300.00, 4000.00, 3400.00,
        7800.00, 4500.00, 6400.00, 4700.00, 3600.00,
        13200.00, 7500.00, 5000.00, 4400.00, 3100.00,
        8900.00, 6300.00, 4200.00, 5200.00, 3700.00,
        9500.00, 7000.00, 4800.00, 4100.00, 3300.00,
        10500.00, 6200.00, 5500.00, 4600.00, 3900.00,
        14000.00, 8100.00, 5400.00, 4500.00, 3000.00,
        8200.00, 4100.00, 6000.00, 4900.00, 3600.00,
        11800.00, 6900.00, 5200.00, 4300.00, 3200.00,
        9300.00, 6500.00, 4700.00, 4800.00, 3500.00,
        10200.00, 7300.00, 4900.00, 4200.00, 3400.00,
        8700.00, 4600.00, 6300.00, 5100.00, 3800.00,
        12100.00, 7800.00, 5300.00, 4400.00, 3100.00,
        9000.00, 6700.00, 4500.00, 5000.00, 3700.00,
        9800.00, 7100.00, 5000.00, 4000.00, 3300.00,
        10800.00, 6400.00, 5600.00, 4700.00, 3900.00,
        14500.00, 8300.00, 5500.00, 4600.00, 3000.00
    ],
    
    'Horas_Trabalhadas': [
        160, 176, 160, 150, 180, 160, 160, 170, 176, 180,
        160, 160, 176, 160, 150, 160, 176, 160, 170, 180,
        150, 160, 176, 160, 180, 160, 160, 160, 176, 170,
        176, 180, 160, 150, 160, 160, 176, 160, 180, 170,
        160, 150, 160, 176, 180, 160, 170, 160, 160, 176,
        160, 176, 160, 150, 180, 160, 160, 170, 176, 180,
        160, 160, 176, 160, 150, 160, 176, 160, 170, 180,
        150, 160, 176, 160, 180, 160, 160, 160, 176, 170,
        176, 180, 160, 150, 160, 160, 176, 160, 180, 170,
        160, 150, 160, 176, 180, 160, 170, 160, 160, 176
    ]
}

df_rh = pd.DataFrame(dados_rh)

# Visualizando as primeiras linhas da base gerada
df_rh.head()

      Funcionario      Departamento  Salario  Horas_Trabalhadas
0       Ana Silva        Tecnologia   8500.0                160
1     Bruno Souza  Recursos Humanos   4200.0                176
2     Carlos Lima        Financeiro   6100.0                160
3   Daniela Costa         Marketing   4800.0                150
4  Eduardo Santos         Operações   3500.0                180

In [2]:
# Salvando o DataFrame em um arquivo do Excel
df_rh.to_excel('base_dados_rh.xlsx', index=False)

print("Base de dados salva como Excel com sucesso!")

Base de dados salva como Excel com sucesso!

In [3]:
# Salvando como CSV (funciona direto, sem precisar do openpyxl)
df_rh.to_csv('base_dados_rh.csv', index=False, encoding='utf-8')

print("Base salva como CSV com sucesso!")

Base salva como CSV com sucesso!

In [9]:
import sweetviz as sv

# Gerando a análise exploratória completa do DataFrame de RH
relatorio_rh = sv.analyze(df_rh)

# Exportando e salvando o relatório como arquivo HTML solicitado
relatorio_rh.show_html("relatorio_rh_sweetviz.html")

print("Relatório Sweetviz gerado e exportado com sucesso como 'ex2_relatorio_rh_sweetviz.html'!")

c:\Users\Clarice\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Done! Use 'show' commands to display/save.   |██████████| [100%]   00:00 -> (00:00 left)

Report relatorio_rh_sweetviz.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.
Relatório Sweetviz gerado e exportado com sucesso como 'ex2_relatorio_rh_sweetviz.html'!

In [10]:
from ydata_profiling import ProfileReport

# Gerando o relatório detalhado
# 'explorative=True' habilita análises profundas de correlação e interação entre variáveis
profile_rh = ProfileReport(df_rh, title="Relatório Detalhado de RH", explorative=True)

# Exibindo o relatório interativo dentro do notebook
display(profile_rh)

# Opcional: Salvar em HTML para enviar ao gerente de RH
profile_rh.to_file("relatorio_rh_ydata.html")

C:\Users\Clarice\AppData\Local\Temp\ipykernel_21596\2688592900.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

ModuleNotFoundError: No module named 'ipywidgets'

100%|██████████| 4/4 [00:00<?, ?it/s]/9 [00:00<00:00, 15.43it/s, Describe variable: Horas_Trabalhadas]
Summarize dataset: 100%|██████████| 14/14 [00:00<00:00, 20.58it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.08s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.08s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 390.57it/s]

In [13]:
# 1. Visão geral: total de linhas e colunas, e quantas linhas não são nulas (não-missing)
print("--- INFORMAÇÕES GERAIS DA BASE ---")
print(df_rh.info())

# 2. Verificando valores ausentes (missing) por coluna
print("\n--- VALORES AUSENTES (MISSING) POR COLUNA ---")
print(df_rh.isnull().sum())

# 3. Verificando nomes repetidos (duplicados)
# Se quiser ver quantas vezes cada nome aparece na coluna de funcionários (ex: 'Funcionario')
print("\n--- Funcionarios MAIS REPETIDOS ---")
print(df_rh['Funcionario'].value_counts().head(10))

--- INFORMAÇÕES GERAIS DA BASE ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Funcionario        100 non-null    object
 1   Departamento       100 non-null    object
 2   Salario            100 non-null    float64
 3   Horas_Trabalhadas  100 non-null    int64
dtypes: float64(1), int64(1), object(2)
memory usage: 3.2+ KB
None

--- VALORES AUSENTES (MISSING) POR COLUNA ---
Funcionario          0
Departamento         0
Salario              0
Horas_Trabalhadas    0
dtype: int64

--- Funcionarios MAIS REPETIDOS ---
Funcionario
Ana Silva            5
Bruno Souza          5
Carlos Lima          5
Daniela Costa        5
Eduardo Santos       5
Fernanda Oliveira    5
Gabriel Pereira      5
Helena Rocha         5
Igor Martins         5
Juliana Alves        5
Name: count, dtype: int64

In [14]:
# Verifica o total atual de linhas na tabela
print(f"Total de linhas na base: {len(df_rh)}")

# Verifica se há linhas exatamente iguais duplicadas
print(f"Linhas duplicadas na tabela: {df_rh.duplicated().sum()}")

Total de linhas na base: 100
Linhas duplicadas na tabela: 2

In [15]:
# Substitua 'Nome' pelo nome real da coluna de funcionários se necessário
# Filtra a tabela para mostrar apenas as linhas dos funcionários que aparecem repetidos
funcionarios_repetidos = df_rh[df_rh['Funcionario'].duplicated(keep=False)]

# Exibe as linhas para você analisar se são idênticas ou diferentes
display(funcionarios_repetidos.sort_values(by='Funcionario'))

      Funcionario      Departamento  Salario  Horas_Trabalhadas
0       Ana Silva        Tecnologia   8500.0                160
80      Ana Silva        Tecnologia   9000.0                176
20      Ana Silva        Tecnologia   7800.0                150
60      Ana Silva        Tecnologia   9300.0                160
40      Ana Silva        Tecnologia  10500.0                160
..            ...               ...      ...                ...
58  Wagner Castro  Recursos Humanos   4300.0                176
98  Wagner Castro  Recursos Humanos   4600.0                160
18  Wagner Castro  Recursos Humanos   4000.0                170
78  Wagner Castro  Recursos Humanos   4400.0                176
38  Wagner Castro  Recursos Humanos   4100.0                180

[100 rows x 4 columns]

In [12]:
# Mostra os nomes reais de todas as colunas da sua tabela
print(df_rh.columns)

Index(['Funcionario', 'Departamento', 'Salario', 'Horas_Trabalhadas'], dtype='object')